import assert from "node:assert/strict";
import test from "node:test";
import { expectedSuffolkChange, expectedSuffolkNetWorth, expectedSuffolkTotals, suffolkAssetControls, suffolkLiabilityControls, suffolkMortgageLeaves } from "./fixtures/suffolk-july-2026.fixture.ts";
const { assignAmountsToPeriods, combineAccountingWords, detectPeriodColumns, formatPeriodAmount, normalizeEquityTableGeometry, parseAccountingAmount, parseOcrFinancialWords, recoverMissingPeriodFromCrop, recoverRowPeriods } = await import("../app/lib/ocrFinancialParser.ts");
const { rotationCandidates, shouldUseOcr } = await import("../app/lib/documentParser.ts");
const { calculatePeriodTotals, calculateReconciliation, confirmedDetailRows } = await import("../app/lib/reportData.ts");
const { calculateStatementTotals, reconcileCategory, sumLeafRows } = await import("../app/lib/reconciliation.ts");

let y=20;const words=[];
function line(text,previous=null,current=null,confidence=94){let x=40;for(const token of text.split(" ")){words.push({text:token,confidence,x0:x,y0:y,x1:x+token.length*8,y1:y+16});x+=token.length*8+7;}if(previous!==null)words.push({text:String(previous),confidence,x0:470,y0:y,x1:550,y1:y+16});if(current!==null)words.push({text:String(current),confidence,x0:870,y0:y,x1:960,y1:y+16});y+=24;}
line("SUFFOLK INDUSTRIAL COMMODITIES INC.");line("NET WORTH");line("EQUITY 30-Jun-26");words.at(-1).x0=470;words.at(-1).x1=550;line("EQUITY 31-Jul-26");words.at(-1).x0=870;words.at(-1).x1=960;
line("REAL ESTATE");line("1177 Yonge St., Toronto 37.50%","300,000","300,000");const propertyY=y-24;words.push({text:"800,000",confidence:94,x0:630,y0:propertyY,x1:700,y1:propertyY+16},{text:"800,000",confidence:94,x0:740,y0:propertyY,x1:810,y1:propertyY+16});line("TOTAL REAL ESTATE","300,000","300,000");
line("INVESTMENTS");line("Kingsberg Plaza (6 Plazas) 6.875%","935,445","935,445");line("Suffolk LP","3,034,311","3,034,311");line("TOTAL INVESTMENTS","3,969,755","3,969,755");
line("LOANS RECEIVABLE");for(const row of [["Dragon Horse - Patrick Chan",100000],["James H. Hutchinson",20000],["Jorlee Holdings",3000000],["Curtis Eisenberg",180650],["George Eisenberg",180650],["Short term loan - Jorlee Holdings",300000]])line(row[0],row[1].toLocaleString("en-US"),row[1].toLocaleString("en-US"));line("3,781,300","3,781,300","3,781,300");
line("MORTGAGES");for(const [description,current,previous] of suffolkMortgageLeaves)line(description,previous===0?"-":previous.toLocaleString("en-US"),current.toLocaleString("en-US"));line("TOTAL MORTGAGES","7,371,085","7,641,069");
line("CORPORATE TAX INSTALMENT");line("Corporate tax instalment","914,386","983,727");line("Corporate tax payable","(914,386)","(983,727)");
line("LOAN PAYABLE - Fleet Street Financial Corp.","(2,280,517)","(2,280,517)");line("LOAN PAYABLE - Ariana Ferrer","(10,000)","(10,000)");line("LOAN PAYABLE - Suffolk LP","(2,200,000)","(3,200,000)");line("SHAREHOLDER ADVANCE - Jay Borkowsky","(950,000)","(950,000)");
line("CIBC Bank","623,646","1,347,353");line("CIBC Bank-Suffolk LP","3,514,156","2,520,363");line("Suffolk LP - receivable","2,200,000","3,200,000");line("TOTAL NET WORTH","16,319,426","16,319,323");line("Page 1");
const parsed=parseOcrFinancialWords(words,"scanned.pdf");const leaves=confirmedDetailRows(parsed.rows);

test("uses the supplied control fixture calculations exactly",()=>{assert.equal(expectedSuffolkTotals.current.assets,23743567);assert.equal(expectedSuffolkTotals.current.liabilities,7424244);assert.equal(expectedSuffolkNetWorth.current,16319323);assert.equal(expectedSuffolkTotals.previous.assets,22674328);assert.equal(expectedSuffolkNetWorth.previous,16319425);assert.equal(expectedSuffolkChange,-102);assert.equal(suffolkAssetControls.length,8);assert.equal(suffolkLiabilityControls.length,5);});
test("implements the supplied leaf and category reconciliation algorithm",()=>{const rows=[{description:"a",category:"Investments",type:"asset",current:935445,previous:935445,isSummary:false,sourceOrder:0},{description:"b",category:"Investments",type:"asset",current:3034311,previous:3034311,isSummary:false,sourceOrder:1},{description:"total",category:"Investments",type:"asset",current:3969755,previous:3969755,isSummary:true,sourceOrder:2}];assert.equal(sumLeafRows(rows,"current"),3969756);const category=reconcileCategory("Investments",rows,3969755,"current");assert.deepEqual(category,{category:"Investments",detailTotal:3969756,sourceControlTotal:3969755,reportedTotal:3969755,difference:1,status:"minor-source-difference"});assert.deepEqual(calculateStatementTotals([category],[]),{assets:3969755,liabilities:0,netWorth:3969755});});
test("handles rotation, OCR fallback, and accounting-number safeguards",()=>{assert.deepEqual(rotationCandidates(270),[270,0,90,180]);assert.equal(shouldUseOcr([]),true);assert.equal(parseAccountingAmount("$ (2,280,517)"),-2280517);assert.equal(parseAccountingAmount("1538000"),1538000);assert.equal(parseAccountingAmount("1.209.488"),1209488);assert.equal(parseAccountingAmount("1177"),null);assert.equal(parseAccountingAmount("37.50%"),null);});
test("does not abort a single-period OCR document that mentions net worth",()=>{const result=parseOcrFinancialWords([{text:"NET",confidence:62,x0:20,y0:20,x1:55,y1:36},{text:"WORTH",confidence:62,x0:60,y0:20,x1:110,y1:36},{text:"Total",confidence:62,x0:20,y0:60,x1:60,y1:76},{text:"Portfolio",confidence:62,x0:65,y0:60,x1:130,y1:76},{text:"Value",confidence:62,x0:135,y0:60,x1:175,y1:76},{text:"$1,209,488",confidence:62,x0:400,y0:60,x1:490,y1:76}],"portfolio.pdf");assert.deepEqual(result.rows,[]);assert.equal(result.averageConfidence,62);});
test("detects dynamic EQUITY comparative columns across intervening valuation columns",()=>{assert.deepEqual(detectPeriodColumns([{text:"August 31, 2026",centerX:100,centerY:20},{text:"EQUITY",centerX:500,centerY:80},{text:"31-Jul-26",centerX:500,centerY:100},{text:"FAIR MARKET VALUE",centerX:650,centerY:80},{text:"PROPERTY MORTGAGE",centerX:760,centerY:80},{text:"NET VALUE",centerX:840,centerY:80},{text:"EQUITY",centerX:950,centerY:80},{text:"31-Aug-26",centerX:950,centerY:100}]),{previousX:500,currentX:950});});
test("selects comparative columns by calendar month rather than physical order",()=>{const columns=detectPeriodColumns([{text:"September 30, 2027",centerX:80,centerY:20},{text:"EQUITY",centerX:480,centerY:80},{text:"30-Sep-27",centerX:480,centerY:100},{text:"FAIR MARKET VALUE",centerX:650,centerY:80},{text:"EQUITY",centerX:920,centerY:80},{text:"31-Aug-27",centerX:920,centerY:100}]);assert.deepEqual(columns,{previousX:920,currentX:480});assert.deepEqual(assignAmountsToPeriods([{value:200,centerX:480,confidence:95},{value:999,centerX:650,confidence:95},{value:100,centerX:920,confidence:95}],columns),{current:200,previous:100});});
test("deskews far-right equity values before assigning them to description rows",()=>{
  const fixture=[];const add=(text,x,y,confidence=94)=>fixture.push({text,confidence,x0:x,y0:y,x1:x+Math.max(18,text.length*7),y1:y+16});
  add("NET",40,20);add("WORTH",75,20);add("EQUITY",470,60);add("31-Jul-26",470,80);add("FAIR",620,60);add("MARKET",660,60);add("VALUE",710,60);add("PROPERTY",760,60);add("MORTGAGE",820,60);add("NET",900,60);add("VALUE",925,60);add("EQUITY",1050,72);add("31-Aug-26",1050,92);
  add("REAL",40,120);add("ESTATE",80,120);
  const estate=[
    ["1177 Yonge St., Toronto",100000,100000,800000],
    ["Kingston Westney - Sutton",283250,283250,2800000],
    ["Pond Mills, London, ON",158000,158000,null],
    ["JJJ Realty Inc.",15000,15000,null],
    ["136 Markland Street",395364,395364,null],
  ];
  estate.forEach(([description,previous,current,fair],index)=>{const rowY=155+index*32;let x=40;for(const token of description.split(" ")){add(token,x,rowY);x+=token.length*7+6;}add(previous.toLocaleString("en-US"),470,rowY);if(fair!==null)add(fair.toLocaleString("en-US"),690,rowY+5);add(current.toLocaleString("en-US"),1050,rowY+12);});
  add("951,614",470,325);add("951,614",1050,337);
  add("INVESTMENTS",40,365);const investments=[["Windstone Property Corp",944625],["Kenedy & 14th Avenue",496540],["Empire LP",2621106]];
  investments.forEach(([description,value],index)=>{const rowY=400+index*32;let x=40;for(const token of description.split(" ")){add(token,x,rowY);x+=token.length*7+6;}add(value.toLocaleString("en-US"),470,rowY);add(value.toLocaleString("en-US"),1050,rowY+12);});
  // Deliberately close to the final leaf: it validates the section but must
  // never replace Empire LP or become an additional account.
  add("4,062,271",470,480);add("4,062,271",1050,492);
  add("TOTAL",40,540);add("NET",85,540);add("WORTH",120,540);add("12,711,655",470,540);add("12,541,337",1050,552);
  const normalized=normalizeEquityTableGeometry(fixture,{previousX:500,currentX:1080});
  assert.ok(normalized.find((word)=>word.text==="100,000"&&word.x0>1000).y0<fixture.find((word)=>word.text==="100,000"&&word.x0>1000).y0);
  const result=parseOcrFinancialWords(fixture,"scanned-table.pdf");
  const realEstate=result.rows.filter((row)=>row.category==="Real Estate");
  assert.deepEqual(realEstate.map((row)=>[row.description,row.previous,row.current]),estate.map(([description,previous,current])=>[description,previous,current]));
  assert.equal(realEstate[0].sourceCategoryControlPrevious,951614);
  assert.equal(realEstate[0].sourceCategoryControlCurrent,951614);
  assert.equal(result.rows.some((row)=>row.current===800000||row.current===2800000),false);
  assert.equal(result.rows.some((row)=>row.description.includes("951,614")),false);
  const parsedInvestments=result.rows.filter((row)=>row.category==="Investments");
  assert.deepEqual(parsedInvestments.map((row)=>[row.description,row.previous,row.current]),investments.map(([description,value])=>[description,value,value]));
  assert.equal(parsedInvestments.find((row)=>row.description==="Empire LP").current,2621106);
  assert.equal(parsedInvestments[0].sourceCategoryControlCurrent,4062271);
  assert.equal(result.rows.some((row)=>row.current===4062271),false);

  const missing=fixture.filter((word)=>!(word.text==="283,250"&&word.x0>1000));
  const missingRows=parseOcrFinancialWords(missing,"missing-current-between-rows.pdf").rows;
  const kingston=missingRows.find((row)=>row.description==="Kingston Westney - Sutton");
  assert.equal(kingston.previous,283250);
  assert.equal(kingston.current,"");
  assert.equal(kingston.needsReview,true);
  assert.deepEqual([missingRows.find((row)=>row.description==="1177 Yonge St., Toronto").current,missingRows.find((row)=>row.description==="Pond Mills, London, ON").current],[100000,158000]);
});
test("produces the same normalized accounts from PNG and scanned-PDF OCR words",()=>{const normalized=(result)=>result.rows.map((row)=>Object.fromEntries(Object.entries(row).filter(([key])=>key!=="source"&&key!=="id")));assert.deepEqual(normalized(parseOcrFinancialWords(words,"statement.png")),normalized(parseOcrFinancialWords(words,"statement.pdf")));});
test("maps July and August independently and reports rather than forces reconciliation",()=>{
  const august=words.map((word)=>{
    if(word.text==="30-Jun-26")return {...word,text:"31-Jul-26"};
    if(word.text==="31-Jul-26")return {...word,text:"31-Aug-26"};
    if(word.text==="16,319,426")return {...word,text:"16,319,323"};
    if(word.text==="16,319,323")return {...word,text:"15,533,188"};
    return {...word};
  });
  const result=parseOcrFinancialWords(august,"suffolk-august.pdf");
  assert.equal(result.rows[0].sourcePreviousDate,"2026-07-31");
  assert.equal(result.rows[0].sourceCurrentDate,"2026-08-31");
  assert.deepEqual([result.rows[0].previous,result.rows[0].current],[300000,300000]);
  const reconciliation=calculateReconciliation(confirmedDetailRows(result.rows));
  assert.equal(reconciliation.source,15_533_188);
  assert.equal(reconciliation.matches,false);
  assert.notEqual(reconciliation.difference,0);
  assert.ok(!result.rows.some((row)=>/total net worth/i.test(row.description)));
  assert.ok(!result.rows.some((row)=>/^\s*300000\b|S\$\s*800/i.test(row.description)));
});
test("does not turn a missed current EQUITY cell into a confident zero",()=>{const target=words.find((word)=>word.text==="1177");const withoutCurrent=words.filter((word)=>!(word.text==="300,000"&&word.x0>850&&Math.abs(word.y0-target.y0)<3));const result=parseOcrFinancialWords(withoutCurrent,"missing-current.pdf");const row=result.rows.find((item)=>item.description==="1177 Yonge St., Toronto");assert.equal(row.current,"");assert.equal(row.previous,300000);assert.equal(row.needsReview,true);});
test("does not omit the opening property and investment leaves",()=>{assert.deepEqual(leaves.slice(0,3).map((row)=>row.description),["1177 Yonge St., Toronto","Kingsberg Plaza (6 Plazas)","Suffolk LP"]);assert.deepEqual([leaves[0].previous,leaves[0].current],[300000,300000]);assert.ok(!leaves.some((row)=>row.current===800000));assert.notEqual(leaves.filter((row)=>row.category==="Investments")[0].description,"Suffolk LP");});
test("keeps banks and general receivables out of mortgages",()=>{for(const description of ["CIBC Bank","CIBC Bank-Suffolk LP","Suffolk LP - receivable"]){const row=leaves.find((item)=>item.description===description);assert.ok(row);assert.notEqual(row.category,"Mortgage Investments / Mortgage Receivables");}assert.equal(leaves.find((row)=>row.description==="CIBC Bank-Suffolk LP").previous,3514156);});
test("retains an unlabeled numeric loans subtotal only as a reconciliation control",()=>{const loans=leaves.filter((row)=>row.category==="Loans Receivable"&&row.description!=="Suffolk LP - receivable");assert.equal(loans.length,6);assert.ok(!leaves.some((row)=>parseAccountingAmount(row.description)!==null));assert.equal(loans[0].sourceCategoryControlCurrent,3781300);assert.equal(loans[0].sourceCategoryControlPrevious,3781300);});
test("preserves every mortgage leaf and treats the 669 Cosburn dash as zero",()=>{const mortgages=leaves.filter((row)=>row.category==="Mortgage Investments / Mortgage Receivables");assert.deepEqual(mortgages.map((row)=>[row.description,row.current,row.previous]),suffolkMortgageLeaves.map((row)=>[...row]));assert.deepEqual({current:mortgages.find((row)=>row.description.includes("669 Cosburn")).current,previous:mortgages.find((row)=>row.description.includes("669 Cosburn")).previous},{current:250000,previous:0});});
test("matches every supplied asset and liability control",()=>{const current=calculatePeriodTotals(leaves,"current"),previous=calculatePeriodTotals(leaves,"previous");const category=(name)=>({category:name,current:current.categories.find((item)=>item.category===name).reportedTotal,previous:previous.categories.find((item)=>item.category===name).reportedTotal});const leaf=(categoryName,description,controlName)=>{const row=leaves.find((item)=>item.category===categoryName&&item.description===description);assert.ok(row,`Missing ${categoryName}: ${description}; got ${leaves.map((item)=>`${item.category}:${item.description}`).join(" | ")}`);return {category:controlName,current:row.current,previous:row.previous??0};};const assets=[category("Real Estate"),category("Investments"),{category:"Loans Receivable",current:leaves.find((row)=>row.description==="Dragon Horse - Patrick Chan").sourceCategoryControlCurrent,previous:leaves.find((row)=>row.description==="Dragon Horse - Patrick Chan").sourceCategoryControlPrevious},category("Mortgage Investments / Mortgage Receivables"),category("Corporate Tax Instalment Receivable"),leaf("Cash & Bank Accounts","CIBC Bank","CIBC Bank"),leaf("Cash & Bank Accounts","CIBC Bank-Suffolk LP","CIBC Bank-Suffolk LP"),leaf("Loans Receivable","Suffolk LP - receivable","Suffolk LP Receivable")];const liabilities=[category("Corporate Tax Payable"),leaf("Loans Payable","LOAN PAYABLE - Fleet Street Financial Corp.","Fleet Street Financial Corp. Loan"),leaf("Loans Payable","LOAN PAYABLE - Ariana Ferrer","Ariana Ferrer Loan"),leaf("Loans Payable","LOAN PAYABLE - Suffolk LP","Suffolk LP Loan"),leaf("Shareholder Advances","SHAREHOLDER ADVANCE - Jay Borkowsky","Shareholder Advance - Jay Borkowsky")];assert.deepEqual(assets,suffolkAssetControls);assert.deepEqual(liabilities,suffolkLiabilityControls);});
test("reports exact published totals using category and overall controls once",()=>{const current=calculatePeriodTotals(leaves,"current"),previous=calculatePeriodTotals(leaves,"previous");assert.deepEqual([current.assets,current.liabilities,current.netWorth],[23743567,7424244,16319323]);assert.deepEqual([previous.assets,previous.liabilities,previous.netWorth],[22674329,6354903,16319426]);assert.equal(current.netWorth-previous.netWorth,-103);assert.equal(current.categories.find((category)=>category.category==="Investments").status,"minor-source-difference");assert.equal(current.categories.find((category)=>category.category==="Mortgage Investments / Mortgage Receivables").status,"minor-source-difference");assert.deepEqual(calculateReconciliation(leaves),{calculated:16319323,source:16319323,difference:0,matches:true});});
test("flags low-confidence values for review",()=>{const uncertain=words.map((word)=>({...word,confidence:word.text==="2,520,363"?42:word.confidence}));assert.equal(parseOcrFinancialWords(uncertain,"scan.pdf").rows.find((row)=>row.current===2520363).needsReview,true);});
test("assigns positioned values to detected previous and current columns",()=>{const columns={previousX:500,currentX:900};assert.deepEqual(assignAmountsToPeriods([{value:3514156,centerX:505,confidence:95},{value:2520363,centerX:905,confidence:95}],columns),{current:2520363,previous:3514156});assert.deepEqual(detectPeriodColumns([{text:"30-Jun-26",centerX:500,centerY:20},{text:"31-Jul-26",centerX:900,centerY:20}]),columns);});
test("chooses the closest equity columns instead of earlier property-analysis values",()=>{assert.deepEqual(assignAmountsToPeriods([{value:300000,centerX:500,confidence:95},{value:800000,centerX:815,confidence:95},{value:300000,centerX:900,confidence:95}],{previousX:500,currentX:900}),{current:300000,previous:300000});});
test("never emits a section heading merged by OCR with the preceding subtotal",()=>{const heading=words.find((word)=>word.text==="LOANS");assert.ok(heading);const merged=[...words,{text:"3,969,755",confidence:90,x0:470,y0:heading.y0,x1:550,y1:heading.y1},{text:"3,969,755",confidence:90,x0:870,y0:heading.y0,x1:960,y1:heading.y1}];const mergedLeaves=confirmedDetailRows(parseOcrFinancialWords(merged,"merged-heading.pdf").rows);assert.ok(!mergedLeaves.some((row)=>/loans? receivable/i.test(row.description)));assert.equal(mergedLeaves.filter((row)=>row.category==="Loans Receivable"&&row.description!=="Suffolk LP - receivable").length,6);});
test("recovers a split CIBC previous value on a displaced OCR baseline",()=>{const original=words.find((word)=>word.text==="3,514,156");assert.ok(original);const displaced=words.filter((word)=>word!==original).map((word)=>word.y0>original.y0?{...word,y0:word.y0+20,y1:word.y1+20}:{...word});displaced.push({text:"3,",confidence:91,x0:470,y0:original.y0+18,x1:490,y1:original.y1+18},{text:"514,",confidence:91,x0:492,y0:original.y0+18,x1:525,y1:original.y1+18},{text:"156",confidence:91,x0:527,y0:original.y0+18,x1:550,y1:original.y1+18});const displacedLeaves=confirmedDetailRows(parseOcrFinancialWords(displaced,"displaced-scan.pdf").rows);const cibc=displacedLeaves.find((row)=>row.description==="CIBC Bank-Suffolk LP");assert.deepEqual({current:cibc.current,previous:cibc.previous,category:cibc.category,institution:cibc.institution},{current:2520363,previous:3514156,category:"Cash & Bank Accounts",institution:"CIBC Bank"});const current=calculatePeriodTotals(displacedLeaves,"current"),previous=calculatePeriodTotals(displacedLeaves,"previous");assert.deepEqual([current.assets,current.liabilities,current.netWorth],[23743567,7424244,16319323]);assert.deepEqual([previous.assets,previous.liabilities,previous.netWorth],[22674329,6354903,16319426]);});
test("retries a missing CIBC period from an upscaled visual-row crop",async()=>{const previousDocument=globalThis.document;const context={fillStyle:"",fillRect(){},drawImage(){}};globalThis.document={createElement(){return {width:0,height:0,getContext(){return context;}};}};try{const recovered=await recoverMissingPeriodFromCrop({width:1000,height:1400},{x0:0,y0:100,x1:1000,y1:120},{current:2520363,previous:null},{previousX:500,currentX:900,tolerance:100},async()=>[{text:"3,514,156",confidence:93,x0:940,y0:32,x1:1100,y1:64}]);assert.deepEqual(recovered,{current:2520363,previous:3514156});}finally{globalThis.document=previousDocument;}});
test("does not recover a following subtotal into the preceding account",async()=>{const previousDocument=globalThis.document;const context={fillStyle:"",fillRect(){},drawImage(){}};globalThis.document={createElement(){return {width:0,height:0,getContext(){return context;}};}};try{const recovered=await recoverMissingPeriodFromCrop({width:1000,height:1400},{x0:0,y0:100,x1:1000,y1:120},{current:null,previous:null},{previousX:500,currentX:900,tolerance:100},async()=>[{text:"7,371,085",confidence:95,x0:940,y0:104,x1:1100,y1:132},{text:"7,641,069",confidence:95,x0:1740,y0:104,x1:1920,y1:132}]);assert.deepEqual(recovered,{current:null,previous:null});}finally{globalThis.document=previousDocument;}});
test("merges split numeric tokens by coordinates and interprets a printed dash as zero",()=>{const token=(text,x0,x1)=>({text,confidence:92,x0,y0:100,x1,y1:116});const rowWords=[token("-",490,510),token("$",870,878),token("250,",880,920),token("000",922,950)];assert.deepEqual(combineAccountingWords(rowWords).map((candidate)=>candidate.value),[0,250000]);assert.deepEqual(recoverRowPeriods(rowWords,{x0:0,y0:95,x1:1000,y1:121},{previousX:500,currentX:910},100).periods,{current:250000,previous:0});});
test("recognizes and normalizes a minor receivable OCR error despite a stale mortgages heading",()=>{const noisy=words.map((word)=>word.text==="receivable"?{...word,text:"receivebl"}:{...word});const row=confirmedDetailRows(parseOcrFinancialWords(noisy,"noisy-receivable.pdf").rows).find((item)=>item.description==="Suffolk LP - receivable");assert.deepEqual({current:row.current,previous:row.previous,category:row.category,holder:row.holder,accountName:row.accountName},{current:3200000,previous:2200000,category:"Loans Receivable",holder:"Suffolk LP",accountName:"Receivable"});});
test("detects period headings reconstructed from split OCR words",()=>{assert.deepEqual(detectPeriodColumns([{text:"30 - Jun - 26",centerX:500,centerY:20},{text:"31 - Jul - 26",centerX:900,centerY:20}]),{previousX:500,currentX:900});});
test("keeps every loan beneath an OCR heading containing scan artifacts",()=>{const noisy=words.map((word)=>word.text==="LOANS"?{...word,text:"|LOANS|"}:word);const noisyLeaves=confirmedDetailRows(parseOcrFinancialWords(noisy,"noisy-scan.pdf").rows);for(const description of ["Dragon Horse - Patrick Chan","James H. Hutchinson","Jorlee Holdings","Curtis Eisenberg","George Eisenberg","Short term loan - Jorlee Holdings"]){const row=noisyLeaves.find((item)=>item.description===description);assert.ok(row,`Missing ${description}`);assert.equal(row.category,"Loans Receivable");assert.notEqual(row.previous,null);assert.notEqual(row.current,"");}});
test("formats populated, zero, and blank monetary cells consistently",()=>{assert.equal(formatPeriodAmount(300000),"$300,000");assert.equal(formatPeriodAmount(-983727),"($983,727)");assert.equal(formatPeriodAmount(0),"$0");assert.equal(formatPeriodAmount(null),"$0");});
test("every parsed account owns separate current and previous properties",()=>{for(const row of leaves){assert.ok(Object.hasOwn(row,"current"));assert.ok(Object.hasOwn(row,"previous"));}});
test("matches the required CIBC and Suffolk receivable period assertions",()=>{
  const findAccount=(description)=>leaves.find((item)=>item.description===description);
  const periods=(row)=>({current:row.current,previous:row.previous});
  assert.deepEqual(periods(findAccount("CIBC Bank")),{current:1_347_353,previous:623_646});
  assert.deepEqual(periods(findAccount("CIBC Bank-Suffolk LP")),{current:2_520_363,previous:3_514_156});
  assert.deepEqual(periods(findAccount("Suffolk LP - receivable")),{current:3_200_000,previous:2_200_000});
  assert.equal(findAccount("Suffolk LP - receivable").category,"Loans Receivable");
  assert.notEqual(findAccount("Suffolk LP - receivable").category,"Mortgage Investments / Mortgage Receivables");
  assert.deepEqual([findAccount("CIBC Bank").category,findAccount("CIBC Bank").institution,findAccount("CIBC Bank").accountName],["Cash & Bank Accounts","CIBC Bank","CIBC Bank"]);
  assert.deepEqual([findAccount("CIBC Bank-Suffolk LP").category,findAccount("CIBC Bank-Suffolk LP").institution,findAccount("CIBC Bank-Suffolk LP").accountName],["Cash & Bank Accounts","CIBC Bank","CIBC Bank-Suffolk LP"]);
  assert.deepEqual([findAccount("Suffolk LP - receivable").institution,findAccount("Suffolk LP - receivable").accountName],["Suffolk LP","Receivable"]);
});
