import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const css=await readFile(new URL("../app/globals.css",import.meta.url),"utf8");
const app=await readFile(new URL("../app/report-app.tsx",import.meta.url),"utf8");
const subscription=await readFile(new URL("../app/lib/subscription.ts",import.meta.url),"utf8");

test("renders the approved executive summary without a duplicate KPI section",()=>{assert.match(app,/className="statementExecutive"/);assert.match(app,/>Net Worth Statement</);assert.match(app,/>Current net worth</);assert.match(app,/>Previous-period net worth</);assert.match(app,/>Change in net worth</);assert.match(app,/>Assets for every \$1 owed</);assert.equal((app.match(/className="wealthOverview"/g)??[]).length,1);});
test("places normalized dynamic asset mix on the executive page",()=>{assert.match(app,/className="executiveAssetMix"/);assert.match(app,/assetMix\.map/);assert.match(app,/entry\.category/);assert.match(app,/entry\.percentage\.toFixed\(1\)/);assert.doesNotMatch(app,/assetMixPage/);});
test("uses a semantic six-column ownership statement",()=>{assert.match(app,/Category \/ Investment Name/);assert.match(app,/rowSpan=\{2\}/);assert.match(app,/colSpan=\{2\} scope="colgroup">Current/);assert.match(app,/colSpan=\{2\} scope="colgroup">Previous/);assert.equal((app.match(/className="statementMoneyColumn"/g)??[]).length,4);assert.match(app,/100% Value/);assert.match(app,/Investor Share/);});
test("renders account ownership, full values, shares, and meaningful holders",()=>{assert.match(app,/ownership\(row\.ownership\)/);assert.match(app,/money\(row\.currentFull\)/);assert.match(app,/money\(row\.currentShare\)/);assert.match(app,/money\(row\.previousFull\)/);assert.match(app,/money\(row\.previousShare\)/);assert.match(app,/account\.holder&&account\.holder!==account\.name/);});
test("renders one subtotal per category and one statement-total footer",()=>{assert.match(app,/Total \{category\.category\}/);assert.equal((app.match(/<tfoot>/g)??[]).length,1);assert.match(app,/className="statementGrandTotal"><th scope="row">Total Assets/);assert.match(app,/className="statementGrandTotal"><th scope="row">Total Liabilities/);assert.match(app,/className="statementNetWorth"><th scope="row">Net Worth/);});
test("uses aligned fixed ownership and money columns",()=>{assert.match(css,/\.investorStatementTable\s*\{[^}]*table-layout:fixed/);assert.match(css,/\.statementOwnershipColumn\s*\{ width:9%/);assert.match(css,/\.statementMoneyColumn\s*\{ width:15\.5%/);assert.match(css,/\.investorStatementTable \.numberCell\s*\{[^}]*text-align:right;[^}]*white-space:nowrap;[^}]*tabular-nums/);});
test("uses the approved restrained investor-statement palette",()=>{assert.match(css,/\.statementSectionRow th\s*\{[^}]*background:#183b6b/);assert.match(css,/\.periodGroupRow th\s*\{[^}]*background:#183b6b/);assert.match(css,/\.periodGroupRow th:nth-last-child[^}]*background:#285584/);assert.match(css,/\.statementCategoryRow th\s*\{[^}]*background:#e5e9ef/);assert.match(css,/\.statementNetWorth th,\.statementNetWorth td\s*\{[^}]*background:#d9ab43/);});
test("prints native A4 portrait with page one unnumbered and page two numbered",()=>{assert.match(css,/@page\s*\{\s*size:A4 portrait;\s*margin:12mm;/);assert.match(app,/const totalPages=schedulePages\.length\+1/);assert.match(app,/<PrintFooter total=\{totalPages\} paid=\{paid\}\/>/);assert.match(app,/page=\{index\+2\}/);assert.match(app,/page\?`Page \$\{page\} of \$\{total\}`:""/);});
test("repeats grouped table headers and avoids splitting statement rows",()=>{assert.match(app,/PrintStatementTable rows=\{rows\}/);assert.match(app,/StatementTableHead currentLabel=\{currentLabel\}/);assert.match(css,/\.printInvestorStatementTable thead\s*\{ display:table-header-group;/);assert.match(css,/\.statementPrintRow\s*\{ break-inside:avoid; page-break-inside:avoid;/);});
test("keeps free branding fail-closed and paid treatment server-controlled",()=>{assert.match(app,/const branding=paid\?"paidPrint":"freePrint"/);assert.match(app,/paid\?"":"Created by ADAVI"/);assert.match(app,/!paid&&<div className="pageWatermark">adavi<\/div>/);assert.doesNotMatch(app,/Educational estimates only/);assert.match(subscription,/import "server-only"/);assert.match(subscription,/return false/);});
test("does not print navigation or editing controls",()=>{assert.match(css,/\.topbar,\.pageSearchPanel,\.hero,\.stepper,\.reportReady,\.screenReport,\.upgradeBackdrop,[^{]*\{\s*display:none!important;/);});
test("supports selected-investor printing from the same statement model",()=>{assert.match(app,/className="printInvestorPicker"/);assert.match(app,/Print selected investors/);assert.match(app,/buildInvestorStatement\(printRows\)/);assert.match(app,/statement=\{printInvestorStatement\}/);assert.match(app,/assetMix=\{printAssetMix\}/);});
test("retains accessible review, ownership, editing, and search controls",()=>{assert.match(app,/role="dialog" aria-modal="true"/);assert.match(app,/Ownership Percentage<input/);assert.match(app,/className="editRowAction"/);assert.match(app,/type="button" className="delete"/);assert.match(app,/role="search"/);assert.match(app,/searchMatchCount \? "Find next" : "Find"/);});
test("allows custom categories without replacing established categories",()=>{assert.match(app,/customCategories, setCustomCategories/);assert.match(app,/placeholder="e\.g\. RRSP"/);assert.match(app,/>Add category<\/button>/);assert.match(app,/categoriesFor\(row\.kind\)\.map/);});
