import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const css=await readFile(new URL("../app/globals.css",import.meta.url),"utf8");
const app=await readFile(new URL("../app/report-app.tsx",import.meta.url),"utf8");
const subscription=await readFile(new URL("../app/lib/subscription.ts",import.meta.url),"utf8");

test("renders the overview, summary, and detailed report in that order",()=>{const overview=app.indexOf('className="printPage reportPage overviewPage"');const summary=app.indexOf('className="printPage reportPage summaryPage"');const detail=app.indexOf('className="printPage reportPage detailedPage"');assert.ok(overview>=0&&overview<summary&&summary<detail);assert.match(app,/title="Net Worth Overview"/);assert.match(app,/title="Net Worth Summary"/);assert.match(app,/title="Net Worth Detailed"/);assert.equal((app.match(/className="wealthOverview"/g)??[]).length,1);});
test("places normalized dynamic asset mix on the executive page",()=>{assert.match(app,/className="executiveAssetMix"/);assert.match(app,/assetMix\.map/);assert.match(app,/entry\.category/);assert.match(app,/entry\.percentage\.toFixed\(1\)/);assert.doesNotMatch(app,/assetMixPage/);});
test("uses a semantic four-column detailed statement",()=>{assert.match(app,/>Investment \/ Account</);assert.equal((app.match(/className="statementPeriodColumn"/g)??[]).length,2);assert.match(app,/>Current<\/th>/);assert.match(app,/>Previous<\/th>/);assert.match(app,/function PeriodValues/);});
test("renders partial ownership and included amounts above their 100 percent values",()=>{assert.match(app,/const partial=account&&row\.ownership!==undefined&&row\.ownership<100/);assert.match(app,/className=\{partial\?"partialOwnership":""\}/);assert.match(app,/partial&&<small>100%<\/small>/);assert.match(app,/<strong>\{money\(share\)\}<\/strong>\{partial&&<small>\{money\(full\?\?0\)\}<\/small>\}/);assert.doesNotMatch(app,/PeriodValues[^\n]*>100%/);assert.match(app,/account\.holder&&account\.holder!==account\.name/);});
test("renders category, section, and net-worth totals from the shared statement model",()=>{assert.match(app,/Total \{category\.category\}/);assert.ok((app.match(/<tfoot>/g)??[]).length>=2);assert.match(app,/className="statementGrandTotal"><th scope="row">Total Assets/);assert.match(app,/className="statementGrandTotal"><th scope="row">Total Liabilities/);assert.match(app,/className="statementNetWorth"><th scope="row">Net Worth/);assert.match(app,/category\.currentShare/);assert.match(app,/category\.previousShare/);});
test("uses aligned fixed ownership and period columns",()=>{assert.match(css,/\.investorStatementTable\s*\{[^}]*table-layout:fixed/);assert.match(css,/\.statementNameColumn\s*\{ width:42%/);assert.match(css,/\.statementOwnershipColumn\s*\{ width:10%/);assert.match(css,/\.statementPeriodColumn\s*\{ width:24%/);assert.match(css,/\.periodCell strong\s*\{[^}]*text-align:right;[^}]*white-space:nowrap/);assert.match(css,/\.periodCell\s*\{[^}]*tabular-nums/);});
test("uses the approved restrained investor-statement palette",()=>{assert.match(css,/\.statementSectionRow th\s*\{[^}]*background:#183b6b/);assert.match(css,/\.periodGroupRow th\s*\{[^}]*background:#183b6b/);assert.match(css,/\.periodGroupRow th:nth-last-child[^}]*background:#285584/);assert.match(css,/\.statementCategoryRow th\s*\{[^}]*background:#e5e9ef/);assert.match(css,/\.statementNetWorth th,\.statementNetWorth td\s*\{[^}]*background:#fff;[^}]*border-top:2px solid #b58a32/);});
test("prints native A4 portrait with independent numbering for all three sections",()=>{assert.match(css,/@page\s*\{\s*size:A4 portrait;\s*margin:10mm 12mm 12mm;/);assert.match(app,/page=\{1\} total=\{1\} paid=\{paid\} type="Net Worth Overview"/);assert.match(app,/page=\{1\} total=\{1\} paid=\{paid\} type="Net Worth Summary"/);assert.match(app,/page=\{index\+1\} total=\{schedulePages.length\}/);assert.match(app,/Page \{page\} of \{total\}/);});
test("repeats grouped table headers and avoids splitting statement rows",()=>{assert.match(app,/PrintStatementTable rows=\{rows\}/);assert.match(app,/<StatementTableHead\/>/);assert.match(css,/\.investorStatementTable thead\s*\{ display:table-header-group;/);assert.match(css,/\.statementPrintRow\s*\{ break-inside:avoid; page-break-inside:avoid;/);});
test("keeps free branding fail-closed and paid treatment server-controlled",()=>{assert.match(app,/const branding=paid\?"paidPrint":"freePrint"/);assert.match(app,/!paid&&<small>Created with adavi · Not tax, legal, accounting, or investment advice<\/small>/);assert.doesNotMatch(app,/Created with adavi\.ai/);assert.match(app,/!paid&&<div className="pageWatermark">adavi<\/div>/);assert.match(subscription,/import "server-only"/);assert.match(subscription,/return false/);});
test("keeps essential print typography readable",()=>{assert.match(css,/\.investorStatementTable\s*\{[^}]*font-size:10pt/);assert.match(css,/\.statementPrint-account th small\s*\{[^}]*font-size:9.5pt/);assert.match(css,/\.printPageFooter\s*\{[^}]*font-size:8.5pt/);});
test("does not print navigation or editing controls",()=>{assert.match(css,/\.topbar,\.pageSearchPanel,\.hero,\.stepper,\.reportReady,\.screenReport,\.upgradeBackdrop,[^{]*\{\s*display:none!important;/);});
test("uses one selected-investor model for identical preview and print output",()=>{assert.match(app,/className="printInvestorPicker"/);assert.match(app,/Print selected investors/);assert.match(app,/deriveSelectedInvestorReport\(rows, investorList, printInvestorIds\)/);assert.ok((app.match(/statement=\{selectedReport\.statement\}/g)??[]).length>=3);assert.ok((app.match(/assetMix=\{selectedReport\.assetMix\}/g)??[]).length>=2);assert.match(app,/<PrintReport reportName=\{selectedReport\.title\}/);assert.match(app,/Select at least one investor to create a statement\./);assert.match(app,/disabled=\{!selectedReport\.hasSelection\}/);});
test("retains accessible review, ownership, editing, and search controls",()=>{assert.match(app,/role="dialog" aria-modal="true"/);assert.match(app,/Ownership Percentage<input/);assert.match(app,/className="editRowAction"/);assert.match(app,/type="button" className="delete"/);assert.match(app,/role="search"/);assert.match(app,/searchMatchCount \? "Find next" : "Find"/);});
test("keeps review actions clickable and search keyboard accessible",()=>{assert.match(app,/aria-label={`Include \${row\.description/);assert.match(app,/window\.confirm\(`Delete/);assert.match(app,/event\.key==="Escape"/);assert.match(app,/querySelector<HTMLElement>\("input,button,select,a"\)/);assert.match(css,/\.reviewTable th:last-child,\.reviewTable td:last-child\s*\{[^}]*position:sticky;[^}]*right:0/);assert.match(css,/input\[type="checkbox"\],\.reviewTable input\[type="radio"\][^{]*\{[^}]*pointer|input\[type="checkbox"\],\.reviewTable input\[type="radio"\][^{]*\{[^}]*z-index:5/);});
test("shows and edits Wood Gundy account review metadata",()=>{assert.match(app,/Account \{row\.accountNumber\} · \{row\.accountName\}/);assert.match(app,/Source page \{row\.sourcePage\}/);assert.match(app,/extraction confidence/);assert.match(app,/Account type<input value=\{editor\.draft\.accountName\}/);});
test("allows custom categories without replacing established categories",()=>{assert.match(app,/customCategories, setCustomCategories/);assert.match(app,/placeholder="e\.g\. RRSP"/);assert.match(app,/>Add category<\/button>/);assert.match(app,/categoriesFor\(row\.kind\)\.map/);});
test("shows the Reports benefits and a non-interactive gold annual plan",()=>{assert.match(app,/<h2 id="upgrade-title">Subscriber benefit<\/h2>/);assert.equal((app.match(/className="subscriberBenefits"/g)??[]).length,1);assert.equal((app.match(/<li><span aria-hidden="true">✓<\/span>/g)??[]).length,3);for(const benefit of ["Save unlimited reports","Download professional PDFs","Access all previous reports"])assert.equal((app.match(new RegExp(benefit,"g"))??[]).length,1);const panel=app.match(/<section className="upgradePanel"[\s\S]*?<\/section>/)?.[0]??"";assert.doesNotMatch(panel,/Download report data as CSV|Print or save PDF without adavi\.ai branding/);assert.match(panel,/className="monthlyPrice"/);assert.match(panel,/className="annualPrice"/);assert.match(panel,/<strong>\$9\.99<\/strong>/);assert.match(panel,/<strong>\$99\.99<\/strong>/);assert.match(panel,/Secure checkout is not available yet/);assert.match(panel,/This build has no authenticated Stripe Checkout, verified webhook, or server-side subscription status\. Paid actions remain locked; no browser setting can enable them\./);assert.doesNotMatch(panel,/<button/);assert.doesNotMatch(panel,/Most popular|Start trial|Subscribe now|Buy now/);assert.match(css,/\.subscriptionPrices \.annualPrice \{[^}]*background:var\(--gold\)/);assert.doesNotMatch(css,/\.subscriptionPrices \.monthlyPrice \{[^}]*background:var\(--gold\)/);assert.match(css,/@media \(max-width:520px\)[^{]*\{[^}]*\.upgradeBackdrop/);});
test("removes family or group setup and keeps investor-derived report titles",()=>{assert.doesNotMatch(app,/Family or group name|groupName/);assert.match(app,/deriveSelectedInvestorReport\(rows, investorList, printInvestorIds\)/);assert.match(app,/reportName=\{selectedReport\.title\}/);assert.match(css,/\.statementIdentity h1 \{[^}]*text-transform:uppercase/);});
test("advertises and accepts the complete supported format list",()=>{assert.match(app,/PDF, JPG, JPEG, PNG, CSV, XLS, XLSX, OCR scans and Adobe-exported statements/);assert.match(app,/accept="\.pdf,\.jpg,\.jpeg,\.png,\.csv,\.xls,\.xlsx,application\/pdf,image\/jpeg,image\/png,text\/csv,application\/vnd\.ms-excel,application\/vnd\.openxmlformats-officedocument\.spreadsheetml\.sheet"/);});
test("uses entered statement-date period labels without an OCR override",()=>{assert.match(app,/reportPeriodLabels\(statementDate\)/);assert.doesNotMatch(app,/setStatementDate\(extractedStatementDate\)/);});
